### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by samuel-rosa** [colearendt/xlsx#127] opened 2019-05-06 11:00 UTC
The __xlxs__ package is a dependency of the __febr__ package.

When `pkgdown::build_site()` is run to build the package website, the following warning message is issued (when processing the `febr2xlsx.Rd` file):

```r
Reading 'man/febr2xlsx.Rd'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.SAXHelper (file:/home/alessandro/Rlibs/xlsxjars/java/poi-ooxml-3.10.1-20140818.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.SAXHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Writing 'reference/febr2xlsx.html'
```

It is the __xlxs__ package that appears to be using `org.apache.poi.util.SAXHelper`. Thus, I guess that you are better qualified than I to report this to its maintainers. (Perhaps you have already reported this.)

**Comment by colearendt** [comment] 2019-07-11 11:18
Thanks for the report! This may be a result of our needing to update the Apache POI library, which I am loathe to do since it has been a very long time since it has been done 😬 Good to have it here to track in any case!!

**Comment by colearendt** [comment] 2019-07-11 11:20
Oops duplicate of #94 - closing and will track there. Thanks again!

**Closed as completed by colearendt** 2019-07-11 11:20 UTC
Labels: duplicate, java-issue
