### ISSUE TITLE
Java Issues with Java 14

### ISSUE THREAD

**Issue by Kamalbusaidi** [colearendt/xlsx#159] opened 2020-04-14 10:19 UTC
Hi,
I have installed the xlsx package on my MacOs and it required a JDK to be part of the prerequisites.  I downloaded the latest offering from Oracle and get the below message when I try to use it.
![Screen Shot 2020-04-14 at 7 16 45 AM](https://user-images.githubusercontent.com/35888108/79213825-e1487500-7e5a-11ea-8bfb-f7b880bdbb5e.png)

Any help is appreciated.
Kamal

**Comment by colearendt** [comment] 2020-04-14 10:48
Thanks for reporting!! This is a duplicate of #154 and #156 . Please install from github with `remotes::install_github("colearendt/xlsx")`, which should solve your issue.

Also, we can leave this issue open so others can find it. I probably need to make a CRAN submission to solve this issue for others.

**Comment by Kamalbusaidi** [comment] 2020-04-14 12:03
Thanks Cole for your prompt response.

I did that and got the below message:
> library("xlsx")
Error: package or namespace load failed for ‘xlsx’ in get(Info[i, 1], envir
= env):
 lazy-load database
'/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xlsx/R/xlsx.rdb'
is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
>

**Comment by colearendt** [comment] 2020-04-14 12:10
This looks like either a bad installation or you need to restart your R session. Try restarting your R session, and perhaps reinstalling / restarting again if that doesn't fix. If you install an R package while the package is loaded, you can run into these types of corrupt documentation / database issues.

**Comment by Kamalbusaidi** [comment] 2020-04-15 03:49
Cole,
Thank you so much.  Restarting the session did the trick.
APPRECIATED!

Regards
Kamal

**Comment by RE-Chief** [comment] 2020-04-18 07:10
Hi Cole,

I have older xls files that I am trying to read into R. I cannot read them into R using any other means so I am trying to use your read.xlsx2 to read them.

I get the following error which I do not understand are you able to help me out please?

Regards Charles

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.IllegalArgumentException: Your InputStream was neither an OLE2 stream, nor an OOXML stream

**Comment by DVicendese** [comment] 2020-08-19 11:04
Hi,

I am using a 64bit PC with  R 4.0.2, R Studio 1.3.1073 and still getting the error message

library(xlsx)
Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry

I have new versions of xlsx, rJava, xlsxjars and reinstalled Java  8.0.2610.12  itself from
https://www.java.com/en/download/manual.jsp

I restatrted the PC, reopened R then ran the following
remotes::install_github("colearendt/xlsx")

and got this message

* installing *source* package 'xlsx' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Execution halted
ERROR: lazy loading failed for package 'xlsx'

How can I tell R where Java is and more importantly how can I get xlsx to work.

Thank you,

Don

**Comment by colearendt** [comment] 2020-09-12 10:30
To users having trouble with `xlsx` and Java version > 14, a fix has been pushed to CRAN, so the latest from CRAN should solve the issue. #168 

---

@DVicendese apologies for missing your message here. This looks like a java issue, and therefore not something particularly focused on `xlsx`. To prove this, try `library(rJava); .jinit()`, which will likely fail the same way. `xlsx` depends on the `rJava` package, so if `rJava` is failing, then `xlsx` will unfortunately not work.

This looks like an issue not even with R, it seems that Java is not installed on your machine in a usable fashion. You can debug that in any number of Java forums, or ask about setting up R with Java in a generic setting like https://community.rstudio.com . The `rJava` forums / issues may be helpful as well, or just searching for your error message in google, duckduckgo, etc.

To find where Java is installed on your computer, you can try searching with Finder, looking around in Program Files, etc. Ultimately typing `java -version` in the CMD prompt / terminal should do something if it is installed properly: 

```
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

There are some lightweight debugging directions for Java here: https://github.com/colearendt/xlsx#common-problems

If you end up flailing too much with the Java dependency (which is admittedly painful for many users), it might be worth trying one of the other R packages that do not depend on Java and still allow interfacing with xlsx files. https://github.com/colearendt/xlsx#issuesmailing-list 

Each package will have its strengths / weaknesses 😄 I hope that helps!!

**Closed as completed by colearendt** 2020-09-12 10:30 UTC

**Comment by DVicendese** [comment] 2020-09-13 23:44
Thanks Cole for taking the time to respond.

I will try your suggestions.

Many regards,

Don
