### ISSUE TITLE
Segfault during installation on Debian 9

### ISSUE THREAD

**Issue by balwierz** [colearendt/xlsx#85] opened 2017-07-26 14:37 UTC
```
* installing *source* package ‘xlsx’ ...
** package ‘xlsx’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Segmentation fault
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/xlsx’
```
To be sure I reinstalled `rJava` and `xlsxjars`

I am using openjdk 8u141-b15-1~deb9u1

/etc/alternatives/javac -> /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
/etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
/etc/alternatives/jar -> /usr/lib/jvm/java-8-openjdk-amd64/bin/jar

**Comment by colearendt** [comment] 2017-07-26 18:30
What kernel version are you using?  See #83 and the related issues in [rJava](https://github.com/s-u/rJava/issues/110).

**Comment by colearendt** [comment] 2017-07-28 11:56
Duplicate of #83 .  Please see the many workarounds and tests in that thread for debugging and diagnosing if it is the same kernel-version issue.  See if there is another kernel release available to you - the most effective fix I have seen is a kernel update to the corrected version.

**Closed as completed by colearendt** 2017-07-28 11:56 UTC
Labels: duplicate
