### ISSUE TITLE
error: unable to load shared object 'miniconda3/lib/R/library/rJava/libs/rJava.so':

### ISSUE THREAD

**Issue by Shicheng-Guo** [colearendt/xlsx#179] opened 2021-07-09 03:16 UTC
I tried to use conda to install xlsx: `conda install -c conda-forge r-xlsx`, however, I receive this error. 
I do have `rJava.so` and `libjvm.so` in the folder. any suggestions?

```
> library("xlsx")
Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/sguo2/miniconda3/lib/R/library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
```

sessioninfo
```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 8 (Core)

Matrix products: default
BLAS/LAPACK: /home/sguo2/miniconda3/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.0
```

**Comment by colearendt** [comment] 2021-07-12 23:34
Hello! I'm sorry to hear about your issue! Unfortunately, I am not familiar with conda or the conda package for xlsx, rJava, etc. You may have better luck heading over to conda forge, the conda community, etc. It looks like the java system library is not being found properly, which I unfortunately cannot do anything about from the R package's point of view. The issue is in how the conda package is being built / the java dependency is being provided.

**Comment by colearendt** [comment] 2022-01-29 04:25
Closing this since there is little I can do in the way of conda 😄  Please let us know if you run into any other issues!

**Closed as completed by colearendt** 2022-01-29 04:25 UTC
